version: '3.9'

services:
  web_api:
    build: .
    container_name: web_api
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    networks:
      - menu_api_network
    depends_on:
      menu_db:
        condition: service_healthy
      menu_cache:
        condition: service_healthy

  web_api_celery:
    build: .
    container_name: web_api_celery
    profiles: ["nonautomatic"]
    command: sh -c "celery -A app.tasks.celery_app:celery_app worker --beat -l INFO"
    volumes:
      - type: bind
        source: ./admin/Menu.xlsx
        target: /app/admin/Menu.xlsx
    networks:
      - menu_api_network
    depends_on:
      menu_api_rabbitmq:
        condition: service_healthy
      menu_db:
        condition: service_healthy
      menu_cache:
        condition: service_healthy

  menu_db:
    image: postgres:15.1-alpine
    container_name: menu_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
    ports:
      - '5632:5432'
    networks:
      - menu_api_network

  menu_cache:
    image: redis:7-alpine
    container_name: menu_cache
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
    ports:
      - '6379:6379'
    networks:
      - menu_api_network
    volumes:
      - redis_cache:/data

  menu_api_rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: menu_api_rabbitmq
    hostname: menu_api_rabbitmq
    profiles: ["nonautomatic"]
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - menu_api_network

networks:
  menu_api_network:
    name: menu_api_network

volumes:
  db_data:
    name: db_data
  redis_cache:
    name: redis_cache
