version: '3.9'

services:
  web_api:
    build: .
    container_name: web_api
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    depends_on:
      - menu_db

  menu_db:
    image: postgres:15.1-alpine
    container_name: menu_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
    name: db_data
