version: '3.9'

services:
  web_api:
    build: .
    container_name: web_api
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    networks:
      - menu_api_network
    depends_on:
      menu_db:
        condition: service_healthy

  menu_db:
    image: postgres:15.1-alpine
    container_name: menu_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    networks:
      - menu_api_network

networks:
  menu_api_network:
    name: menu_api_network

volumes:
  db_data:
    name: db_data
