"""create tables

Revision ID: 02f9f3e4df84
Revises:
Create Date: 2023-07-24 23:40:00.015277

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '02f9f3e4df84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(length=200), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('submenu',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(length=200), nullable=False),
                    sa.Column('menu_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dish',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=300), nullable=False),
                    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('submenu_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['submenu_id'], ['submenu.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    op.drop_table('submenu')
    op.drop_table('menu')
    # ### end Alembic commands ###
